"use client";
import Image from "next/image";
import { useState } from "react";
import type { CollectionDefinition, PokemonCard, TrainerId } from "@/lib/types";

export default function CardSearch({ onAdd, onWishlist, onClose, canEdit = true, collections }: { onAdd: (card: PokemonCard, trainer: TrainerId) => Promise<boolean>; onWishlist: (card: PokemonCard) => Promise<void>; onClose: () => void; canEdit?: boolean; collections: CollectionDefinition[] }) {
  const [query, setQuery] = useState(""); const [cards, setCards] = useState<PokemonCard[]>([]); const [selected, setSelected] = useState<PokemonCard | null>(null); const [loading, setLoading] = useState(false); const [addingTrainer, setAddingTrainer] = useState<TrainerId | null>(null); const [doneTrainer, setDoneTrainer] = useState<TrainerId | null>(null); const [message, setMessage] = useState("");
  async function search(e: React.FormEvent) { e.preventDefault(); if (!query.trim()) return; setLoading(true); setMessage(""); const response = await fetch(`/api/cards/search?q=${encodeURIComponent(query.trim())}`); const body = await response.json(); setCards(body.data ?? []); setLoading(false); if (!body.data?.length) setMessage("No cards found. Try another Pokémon name!"); }
  async function add(trainer: TrainerId) { if (!selected || addingTrainer) return; setAddingTrainer(trainer); setDoneTrainer(null); const added = await onAdd(selected, trainer); setAddingTrainer(null); if (added) { setDoneTrainer(trainer); setMessage(`${selected.name} joined ${collections.find((item) => item.id === trainer)?.name}'s collection! 🎉`); } }
  async function wish() { if (!selected) return; await onWishlist(selected); setMessage(`${selected.name} was added to your wishlist! ⭐`); }
  return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="Search Pokémon cards"><div className="search-modal"><button className="close-button" onClick={onClose} aria-label="Close search">×</button><p className="eyebrow">Pokédex Search</p><h2>Catch your next card</h2><form onSubmit={search} className="search-form"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Try Pikachu or Charizard…" autoFocus aria-label="Card name"/><button>{loading ? "Searching…" : "Search"}</button></form>{message && <p className="search-message">{message}</p>}<div className="card-results">{cards.map((card) => <button key={card.id} className="result-card" onClick={() => { setSelected(card); setDoneTrainer(null); }}><Image src={card.images.small} alt={card.name} width={245} height={342}/><b>{card.name}</b><small>{card.set.name} · #{card.number}</small></button>)}</div></div>{selected && <div className="detail-panel"><button className="close-button" onClick={() => setSelected(null)} aria-label="Close details">×</button><Image src={selected.images.large} alt={selected.name} width={360} height={502} className="detail-image"/><div><p className="eyebrow">{selected.set.name} · #{selected.number}</p><h2>{selected.name}</h2><div className="detail-facts"><span>❤️ HP {selected.hp ?? "—"}</span><span>✨ {selected.rarity ?? "Unknown rarity"}</span><span>🎨 {selected.artist ?? "Unknown artist"}</span><span>⚔️ {selected.types?.join(", ") ?? "Colorless"}</span></div>{canEdit ? <><button className="wishlist-button" onClick={wish}>⭐ Add to Wishlist</button><h3>Add to a binder</h3><div className="add-buttons">{collections.map((collection) => <button key={collection.id} onClick={() => add(collection.id)} disabled={Boolean(addingTrainer)} className={doneTrainer === collection.id ? "done-button" : ""}>{addingTrainer === collection.id ? "Adding…" : doneTrainer === collection.id ? "✓ Done!" : `${collection.badge} ${collection.name}`}</button>)}</div></> : <p className="visitor-note">🔒 Admin Sign In is required to add cards.</p>}</div></div>}</div>;
}
