"use client";
import Image from "next/image";
import { useState } from "react";
import type { PokemonCard, TrainerId } from "@/lib/types";
import { trainers } from "@/lib/trainers";

export default function CardSearch({ onAdd, onClose }: { onAdd: (card: PokemonCard, trainer: TrainerId) => Promise<void>; onClose: () => void }) {
  const [query, setQuery] = useState(""); const [cards, setCards] = useState<PokemonCard[]>([]); const [selected, setSelected] = useState<PokemonCard | null>(null); const [loading, setLoading] = useState(false); const [message, setMessage] = useState("");
  async function search(e: React.FormEvent) { e.preventDefault(); if (!query.trim()) return; setLoading(true); setMessage(""); const response = await fetch(`/api/cards/search?q=${encodeURIComponent(query.trim())}`); const body = await response.json(); setCards(body.data ?? []); setLoading(false); if (!body.data?.length) setMessage("No cards found. Try another Pokémon name!"); }
  async function add(trainer: TrainerId) { if (!selected) return; await onAdd(selected, trainer); setMessage(`${selected.name} joined ${trainers.find((t) => t.id === trainer)?.name}'s collection! 🎉`); }
  return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="Search Pokémon cards"><div className="search-modal"><button className="close-button" onClick={onClose} aria-label="Close search">×</button><p className="eyebrow">Pokédex Search</p><h2>Catch your next card</h2><form onSubmit={search} className="search-form"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Try Pikachu or Charizard…" autoFocus aria-label="Card name"/><button>{loading ? "Searching…" : "Search"}</button></form>{message && <p className="search-message">{message}</p>}<div className="card-results">{cards.map((card) => <button key={card.id} className="result-card" onClick={() => setSelected(card)}><Image src={card.images.small} alt={card.name} width={245} height={342}/><b>{card.name}</b><small>{card.set.name} · #{card.number}</small></button>)}</div></div>{selected && <div className="detail-panel"><button className="close-button" onClick={() => setSelected(null)} aria-label="Close details">×</button><Image src={selected.images.large} alt={selected.name} width={360} height={502} className="detail-image"/><div><p className="eyebrow">{selected.set.name} · #{selected.number}</p><h2>{selected.name}</h2><div className="detail-facts"><span>❤️ HP {selected.hp ?? "—"}</span><span>✨ {selected.rarity ?? "Unknown rarity"}</span><span>🎨 {selected.artist ?? "Unknown artist"}</span><span>⚔️ {selected.types?.join(", ") ?? "Colorless"}</span></div><h3>Add to a binder</h3><div className="add-buttons">{trainers.map((trainer) => <button key={trainer.id} onClick={() => add(trainer.id)}>{trainer.badge} {trainer.name}</button>)}</div></div></div>}</div>;
}
