"use client";
import { useEffect, useMemo, useState } from "react";
import Image from "next/image";
import type { CollectionDefinition, Collections, CollectionState, PokemonCard, TrainerId } from "@/lib/types";
import TrainerCard from "./TrainerCard"; import CardSearch from "./CardSearch"; import CardScanner from "./CardScanner"; import Achievements from "./Achievements"; import FamilyLogin from "./FamilyLogin";

export default function PokemonWorld() {
  const [collections, setCollections] = useState<Collections>({}); const [definitions, setDefinitions] = useState<CollectionDefinition[]>([]); const [editableIds, setEditableIds] = useState<string[]>([]); const [adminEmail, setAdminEmail] = useState(""); const [wishlist, setWishlist] = useState<PokemonCard[]>([]);
  const [searchOpen, setSearchOpen] = useState(false); const [scannerOpen, setScannerOpen] = useState(false); const [activeBinder, setActiveBinder] = useState<TrainerId | null>(null); const [cloudMode, setCloudMode] = useState(false); const [accessToken, setAccessToken] = useState(""); const [notice, setNotice] = useState(""); const [newCollection, setNewCollection] = useState("");
  const authHeaders = (token = accessToken): Record<string, string> => token ? { Authorization: `Bearer ${token}` } : {};
  async function load(token = accessToken) {
    const headers: Record<string, string> = token ? { Authorization: `Bearer ${token}` } : {};
    const response = await fetch("/api/collections", { cache: "no-store", headers });
    if (response.ok) { const body = await response.json() as CollectionState; setCollections(body.collections); setDefinitions(body.definitions); setEditableIds(body.editableIds); setAdminEmail(body.adminEmail ?? ""); }
    if (token) { const wish = await fetch("/api/wishlist", { cache: "no-store", headers }); if (wish.ok) setWishlist((await wish.json()).cards ?? []); } else setWishlist([]);
  }
  useEffect(() => { load(""); fetch("/api/auth/config").then((response) => response.json()).then((body) => setCloudMode(body.cloudMode)); }, []);
  const total = useMemo(() => Object.values(collections).flat().reduce((sum, item) => sum + item.quantity, 0), [collections]);
  const editableDefinitions = definitions.filter((item) => editableIds.includes(item.id)); const canEdit = !cloudMode || Boolean(accessToken);
  async function addCard(card: PokemonCard, trainer: TrainerId) { if (!editableIds.includes(trainer)) return setNotice("This admin cannot edit that binder."); const response = await fetch("/api/collections", { method: "POST", headers: { "Content-Type": "application/json", ...authHeaders() }, body: JSON.stringify({ trainer, card }) }); if (!response.ok) return setNotice((await response.json()).error ?? "Admin sign-in expired."); await load(); }
  async function removeCard(cardId: string, trainer: TrainerId) { if (!editableIds.includes(trainer)) return; const response = await fetch("/api/collections", { method: "DELETE", headers: { "Content-Type": "application/json", ...authHeaders() }, body: JSON.stringify({ trainer, cardId }) }); if (!response.ok) return setNotice("That binder could not be changed."); await load(); }
  async function createCollection(event: React.FormEvent) { event.preventDefault(); if (!newCollection.trim()) return; const response = await fetch("/api/collections", { method: "POST", headers: { "Content-Type": "application/json", ...authHeaders() }, body: JSON.stringify({ action: "create", name: newCollection }) }); const body = await response.json(); if (!response.ok) return setNotice(body.error ?? "Could not create that binder."); setNewCollection(""); await load(); setNotice("New binder created! 📘"); }
  async function addWishlist(card: PokemonCard) { const response = await fetch("/api/wishlist", { method: "POST", headers: { "Content-Type": "application/json", ...authHeaders() }, body: JSON.stringify({ card }) }); if (response.ok) setWishlist((await response.json()).cards); }
  async function removeWishlist(cardId: string) { const response = await fetch("/api/wishlist", { method: "DELETE", headers: { "Content-Type": "application/json", ...authHeaders() }, body: JSON.stringify({ cardId }) }); if (response.ok) setWishlist((await response.json()).cards); }
  const currentDefinition = definitions.find((item) => item.id === activeBinder); const activeItems = activeBinder ? collections[activeBinder] ?? [] : [];
  const typeGroups = useMemo(() => { const groups = new Map<string, typeof activeItems>(); for (const item of activeItems) { const type = item.card.types?.[0] ?? "Colorless"; if (!groups.has(type)) groups.set(type, []); groups.get(type)!.push(item); } for (const items of groups.values()) items.sort((a, b) => a.card.name.localeCompare(b.card.name)); return Array.from(groups.entries()).sort(([a], [b]) => a.localeCompare(b)); }, [activeItems]);
  return <main className="site-shell"><div className="ambient ambient-one"/><div className="ambient ambient-two"/><div className="page-wrap"><header className="hero"><div><span className="hero-pill">⚡ Family Trainer HQ</span><h1>Pokémon World Deluxe</h1><p>Open the family binder, discover real cards, and collect together.</p></div><div className="hero-side"><div className="hero-stats"><div><strong>{total}</strong><span>Family Cards</span></div><div><strong>{definitions.length}</strong><span>Collections</span></div></div>{cloudMode && <FamilyLogin accessToken={accessToken} onLogin={(token) => { setAccessToken(token); load(token); setNotice("Admin editing unlocked! 🎉"); }} onLogout={() => { setAccessToken(""); load(""); }}/>}</div></header>{notice && <button className="notice-banner" onClick={() => setNotice("")}>{notice} <span>×</span></button>}
  {!canEdit && <section className="visitor-banner"><b>👀 Visitor Mode</b><span>Browse every binder. Admin sign-in is needed to make changes.</span></section>}
  <section className="collection-section"><div className="section-heading"><div><p className="eyebrow">Choose a Trainer</p><h2>Family Collections</h2></div><div className="header-actions">{canEdit && editableDefinitions.length > 0 && <button className="secondary-button" onClick={() => setScannerOpen(true)}>📷 Scan Binder</button>}<button className="primary-button" onClick={() => setSearchOpen(true)}>🔎 Search Cards</button></div></div>{canEdit && <form className="new-collection-form" onSubmit={createCollection}><input value={newCollection} onChange={(event) => setNewCollection(event.target.value)} placeholder="Name a new binder…" maxLength={40}/><button className="primary-button">＋ Create Collection</button></form>}<div className="trainer-grid">{definitions.map((definition) => <TrainerCard key={definition.id} trainer={definition} items={collections[definition.id] ?? []} editable={editableIds.includes(definition.id)} onOpen={setActiveBinder}/>)}</div></section>
  {canEdit && <section className="wishlist-section"><div><p className="eyebrow">Dream Cards</p><h2>⭐ {adminEmail ? `${adminEmail.split("@")[0]}'s` : "Admin"} Wishlist</h2><p>Add cards from Pokédex Search without putting them inside a collection.</p></div>{wishlist.length === 0 ? <p className="wishlist-empty">No dream cards yet—search for one!</p> : <div className="wishlist-grid">{wishlist.map((card) => <div key={card.id}><Image src={card.images.small} alt={card.name} width={160} height={224}/><b>{card.name}</b><button onClick={() => removeWishlist(card.id)}>Remove</button></div>)}</div>}</section>}
  <Achievements collections={canEdit ? Object.fromEntries(editableIds.map((id) => [id, collections[id] ?? []])) : collections} adminEmail={adminEmail} wishlist={wishlist}/>{canEdit && <section className="toolbox"><div><p className="eyebrow">Next Mission</p><h2>Fill a binder page!</h2><p>Photograph up to 18 cards, check the matches, and add them together.</p></div>{editableDefinitions.length > 0 && <button className="primary-button" onClick={() => setScannerOpen(true)}>Open Scanner →</button>}</section>}<footer>Built by Leo and Remy Ramchandani</footer></div>
  {searchOpen && <CardSearch canEdit={canEdit && editableDefinitions.length > 0} collections={editableDefinitions} onAdd={addCard} onWishlist={addWishlist} onClose={() => setSearchOpen(false)}/>} {scannerOpen && canEdit && <CardScanner accessToken={accessToken} collections={editableDefinitions} onAdd={addCard} onClose={() => setScannerOpen(false)}/>} {activeBinder && currentDefinition && <div className="modal-backdrop" role="dialog" aria-modal="true"><div className="binder-modal real-binder"><button className="close-button" onClick={() => setActiveBinder(null)}>×</button><p className="eyebrow">{currentDefinition.badge} {currentDefinition.title}</p><h2>{currentDefinition.name}&apos;s Binder</h2>{activeItems.length === 0 ? <div className="empty-binder"><span>📖</span><h3>This binder is ready!</h3><p>{editableIds.includes(activeBinder) ? "Search or scan to make the first catch." : "No cards have been added yet."}</p></div> : typeGroups.map(([type, items]) => <section className={`binder-type type-${type.toLowerCase()}`} key={type}><h3>{type} Pokémon</h3><div className="binder-page">{items.map((item) => <div key={item.card.id} className="binder-card sleeve">{item.quantity > 1 && <span className="copy-count">×{item.quantity}</span>}<Image src={item.card.images.small} alt={item.card.name} width={245} height={342}/><b>{item.card.name}</b><small>{item.quantity} {item.quantity === 1 ? "copy" : "copies"}</small>{editableIds.includes(activeBinder) && <button className="remove-button" onClick={() => removeCard(item.card.id, activeBinder)}>− Remove one</button>}</div>)}</div></section>)}</div></div>}</main>;
}
