"use client";
import { useEffect, useMemo, useState } from "react";
import Image from "next/image";
import type { AdminBadgeProfile, CollectionDefinition, Collections, CollectionState, PokemonCard, TrainerId } from "@/lib/types";
import TrainerCard from "./TrainerCard"; import CardSearch from "./CardSearch"; import CardScanner from "./CardScanner"; import Achievements from "./Achievements"; import FamilyLogin from "./FamilyLogin";

const partnerChoices = ["Pikachu", "Charizard", "Bulbasaur", "Squirtle", "Eevee", "Mewtwo", "Gengar", "Lucario"];
const powerChoices = ["Card Hunter", "Lucky Pulls", "Legendary Finds", "Holo Seeker", "Set Master", "Trade Expert"];
const binderPages = <T,>(items: T[]) => Array.from({ length: Math.ceil(items.length / 9) }, (_, page) => items.slice(page * 9, page * 9 + 9));

export default function PokemonWorld() {
  const [collections, setCollections] = useState<Collections>({}); const [definitions, setDefinitions] = useState<CollectionDefinition[]>([]); const [editableIds, setEditableIds] = useState<string[]>([]); const [adminEmail, setAdminEmail] = useState(""); const [badgeAdmins, setBadgeAdmins] = useState<AdminBadgeProfile[]>([]); const [wishlist, setWishlist] = useState<PokemonCard[]>([]);
  const [searchOpen, setSearchOpen] = useState(false); const [scannerOpen, setScannerOpen] = useState(false); const [activeBinder, setActiveBinder] = useState<TrainerId | null>(null); const [editingTrainer, setEditingTrainer] = useState<CollectionDefinition | null>(null); const [editPartner, setEditPartner] = useState(""); const [editPower, setEditPower] = useState(""); const [editPhoto, setEditPhoto] = useState<File | null>(null); const [cloudMode, setCloudMode] = useState(false); const [accessToken, setAccessToken] = useState(""); const [notice, setNotice] = useState(""); const [newCollection, setNewCollection] = useState(""); const [newPartner, setNewPartner] = useState(partnerChoices[0]); const [newPower, setNewPower] = useState(powerChoices[0]); const [newPhoto, setNewPhoto] = useState<File | null>(null);
  const authHeaders = (token = accessToken): Record<string, string> => token ? { Authorization: `Bearer ${token}` } : {};
  async function load(token = accessToken) {
    const headers: Record<string, string> = token ? { Authorization: `Bearer ${token}` } : {};
    const response = await fetch("/api/collections", { cache: "no-store", headers });
    if (response.ok) { const body = await response.json() as CollectionState; setCollections(body.collections); setDefinitions(body.definitions); setEditableIds(body.editableIds); setAdminEmail(body.adminEmail ?? ""); setBadgeAdmins(body.badgeAdmins ?? []); }
    if (token) { const wish = await fetch("/api/wishlist", { cache: "no-store", headers }); if (wish.ok) setWishlist((await wish.json()).cards ?? []); } else setWishlist([]);
  }
  useEffect(() => { load(""); fetch("/api/auth/config").then((response) => response.json()).then((body) => setCloudMode(body.cloudMode)); }, []);
  const total = useMemo(() => Object.values(collections).flat().reduce((sum, item) => sum + item.quantity, 0), [collections]);
  const editableDefinitions = definitions.filter((item) => editableIds.includes(item.id)); const canEdit = !cloudMode || Boolean(accessToken);
  async function addCard(card: PokemonCard, trainer: TrainerId) { if (!editableIds.includes(trainer)) { setNotice("This admin cannot edit that binder."); return false; } const response = await fetch("/api/collections", { method: "POST", headers: { "Content-Type": "application/json", ...authHeaders() }, body: JSON.stringify({ trainer, card }) }); if (!response.ok) { setNotice((await response.json()).error ?? "Admin sign-in expired."); return false; } await load(); return true; }
  async function removeCard(cardId: string, trainer: TrainerId) { if (!editableIds.includes(trainer)) return; const response = await fetch("/api/collections", { method: "DELETE", headers: { "Content-Type": "application/json", ...authHeaders() }, body: JSON.stringify({ trainer, cardId }) }); if (!response.ok) return setNotice("That binder could not be changed."); await load(); }
  async function createCollection(event: React.FormEvent) { event.preventDefault(); if (!newCollection.trim()) return; const form = new FormData(); form.append("name", newCollection); form.append("partnerPokemon", newPartner); form.append("ability", newPower); if (newPhoto) form.append("photo", newPhoto); const response = await fetch("/api/collections", { method: "POST", headers: authHeaders(), body: form }); const body = await response.json(); if (!response.ok) return setNotice(body.error ?? "Could not create that binder."); setNewCollection(""); setNewPhoto(null); await load(); setNotice("New binder created! 📘"); }
  function openProfileEditor(trainer: CollectionDefinition) { setEditingTrainer(trainer); setEditPartner(trainer.partnerPokemon ?? partnerChoices[0]); setEditPower(trainer.ability ?? powerChoices[0]); setEditPhoto(null); }
  async function saveProfile(event: React.FormEvent) { event.preventDefault(); if (!editingTrainer) return; const form = new FormData(); form.append("trainer", editingTrainer.id); form.append("partnerPokemon", editPartner); form.append("ability", editPower); if (editPhoto) form.append("photo", editPhoto); const response = await fetch("/api/collections", { method: "PATCH", headers: authHeaders(), body: form }); const body = await response.json(); if (!response.ok) return setNotice(body.error ?? "Could not update that profile."); setEditingTrainer(null); await load(); setNotice("Trainer profile updated! ✨"); }
  async function addWishlist(card: PokemonCard) { const response = await fetch("/api/wishlist", { method: "POST", headers: { "Content-Type": "application/json", ...authHeaders() }, body: JSON.stringify({ card }) }); if (response.ok) setWishlist((await response.json()).cards); }
  async function removeWishlist(cardId: string) { const response = await fetch("/api/wishlist", { method: "DELETE", headers: { "Content-Type": "application/json", ...authHeaders() }, body: JSON.stringify({ cardId }) }); if (response.ok) setWishlist((await response.json()).cards); }
  const currentDefinition = definitions.find((item) => item.id === activeBinder); const activeItems = activeBinder ? collections[activeBinder] ?? [] : [];
  const sortedDefinitions = useMemo(() => [...definitions].sort((a, b) => { const xp = (id: string) => (collections[id] ?? []).reduce((sum, item) => sum + item.quantity, 0) * 20; return xp(b.id) - xp(a.id) || a.name.localeCompare(b.name); }), [definitions, collections]);
  const typeGroups = useMemo(() => { const groups = new Map<string, typeof activeItems>(); for (const item of activeItems) { const type = item.card.types?.[0] ?? "Colorless"; if (!groups.has(type)) groups.set(type, []); groups.get(type)!.push(item); } for (const items of groups.values()) items.sort((a, b) => a.card.name.localeCompare(b.card.name)); return Array.from(groups.entries()).sort(([a], [b]) => a.localeCompare(b)); }, [activeItems]);
  return <main className="site-shell"><div className="ambient ambient-one"/><div className="ambient ambient-two"/><div className="page-wrap"><header className="hero"><div><span className="hero-pill">⚡ Family Trainer HQ</span><h1>Pokémon World Deluxe</h1><p>Open the family binder, discover real cards, and collect together.</p></div><div className="hero-side"><div className="hero-stats"><div><strong>{total}</strong><span>Family Cards</span></div><div><strong>{definitions.length}</strong><span>Collections</span></div></div>{cloudMode && <FamilyLogin accessToken={accessToken} onLogin={(token) => { setAccessToken(token); load(token); setNotice("Admin editing unlocked! 🎉"); }} onLogout={() => { setAccessToken(""); load(""); }}/>}</div></header>{notice && <button className="notice-banner" onClick={() => setNotice("")}>{notice} <span>×</span></button>}
  {!canEdit && <section className="visitor-banner"><b>👀 Visitor Mode</b><span>Browse every binder. Admin sign-in is needed to make changes.</span></section>}
  <section className="collection-section"><div className="section-heading"><div><p className="eyebrow">Choose a Trainer</p><h2>Family Collections</h2></div><div className="header-actions">{canEdit && editableDefinitions.length > 0 && <button className="secondary-button" onClick={() => setScannerOpen(true)}>📷 Scan Binder</button>}<button className="primary-button" onClick={() => setSearchOpen(true)}>🔎 Search Cards</button></div></div>{canEdit && <form className="new-collection-form" onSubmit={createCollection}><input value={newCollection} onChange={(event) => setNewCollection(event.target.value)} placeholder="Name a new binder…" maxLength={40} required/><label>Partner<select value={newPartner} onChange={(event) => setNewPartner(event.target.value)}>{partnerChoices.map((choice) => <option key={choice}>{choice}</option>)}</select></label><label>Power<select value={newPower} onChange={(event) => setNewPower(event.target.value)}>{powerChoices.map((choice) => <option key={choice}>{choice}</option>)}</select></label><label className="photo-choice">Trainer Photo<input type="file" accept="image/jpeg,image/png" onChange={(event) => setNewPhoto(event.target.files?.[0] ?? null)}/></label><button className="primary-button">＋ Create Collection</button></form>}<div className="trainer-grid">{sortedDefinitions.map((definition) => <TrainerCard key={definition.id} trainer={definition} items={collections[definition.id] ?? []} editable={editableIds.includes(definition.id)} onOpen={setActiveBinder} onEdit={openProfileEditor}/>)}</div></section>
  {canEdit && <section className="wishlist-section"><div><p className="eyebrow">Dream Cards</p><h2>⭐ {adminEmail ? `${adminEmail.split("@")[0]}'s` : "Admin"} Wishlist</h2><p>Add cards from Pokédex Search without putting them inside a collection.</p></div>{wishlist.length === 0 ? <p className="wishlist-empty">No dream cards yet—search for one!</p> : <div className="wishlist-grid">{wishlist.map((card) => <div key={card.id}><Image src={card.images.small} alt={card.name} width={160} height={224}/><b>{card.name}</b><button onClick={() => removeWishlist(card.id)}>Remove</button></div>)}</div>}</section>}
  <Achievements collections={collections} admins={badgeAdmins}/>{canEdit && <section className="toolbox"><div><p className="eyebrow">Next Mission</p><h2>Fill a binder page!</h2><p>Photograph up to 18 cards, check the matches, and add them together.</p></div>{editableDefinitions.length > 0 && <button className="primary-button" onClick={() => setScannerOpen(true)}>Open Scanner →</button>}</section>}<footer>Built by Leo and Remy Ramchandani</footer></div>
  {editingTrainer && <div className="modal-backdrop profile-editor-layer"><form className="profile-editor" onSubmit={saveProfile}><button type="button" className="close-button" onClick={() => setEditingTrainer(null)}>×</button><p className="eyebrow">Trainer Profile</p><h2>Change {editingTrainer.name}&apos;s Profile</h2><label>Partner<select value={editPartner} onChange={(event) => setEditPartner(event.target.value)}>{partnerChoices.map((choice) => <option key={choice}>{choice}</option>)}</select></label><label>Power<select value={editPower} onChange={(event) => setEditPower(event.target.value)}>{powerChoices.map((choice) => <option key={choice}>{choice}</option>)}</select></label><label>New Picture (optional)<input type="file" accept="image/jpeg,image/png" onChange={(event) => setEditPhoto(event.target.files?.[0] ?? null)}/></label><button className="primary-button">Save Profile</button></form></div>}
  {searchOpen && <CardSearch canEdit={canEdit && editableDefinitions.length > 0} collections={editableDefinitions} onAdd={addCard} onWishlist={addWishlist} onClose={() => setSearchOpen(false)}/>} {scannerOpen && canEdit && <CardScanner accessToken={accessToken} collections={editableDefinitions} onAdd={addCard} onClose={() => setScannerOpen(false)}/>} {activeBinder && currentDefinition && <div className="modal-backdrop" role="dialog" aria-modal="true"><div className="binder-modal real-binder"><button className="close-button" onClick={() => setActiveBinder(null)}>×</button><p className="eyebrow">{currentDefinition.badge} {currentDefinition.title}</p><h2>{currentDefinition.name}&apos;s Binder</h2>{activeItems.length === 0 ? <div className="empty-binder"><span>📖</span><h3>This binder is ready!</h3><p>{editableIds.includes(activeBinder) ? "Search or scan to make the first catch." : "No cards have been added yet."}</p></div> : typeGroups.map(([type, items]) => <section className={`binder-type type-${type.toLowerCase()}`} key={type}><h3>{type} Pokémon</h3>{binderPages(items).map((page, pageIndex) => <div className="binder-page-wrap" key={`${type}-${pageIndex}`}><div className="binder-page-label">Page {pageIndex + 1} · Nine-pocket sleeve</div><div className="binder-page">{page.map((item) => <div key={item.card.id} className="binder-card sleeve">{item.quantity > 1 && <span className="copy-count">×{item.quantity}</span>}<Image src={item.card.images.large} alt={item.card.name} width={360} height={502} sizes="(min-width: 900px) 25vw, 42vw"/><b>{item.card.name}</b><small>{item.quantity} {item.quantity === 1 ? "copy" : "copies"}</small>{editableIds.includes(activeBinder) && <button className="remove-button" onClick={() => removeCard(item.card.id, activeBinder)}>− Remove one</button>}</div>)}</div></div>)}</section>)}</div></div>}</main>;
}
